### ISSUE TITLE
MQTT credentials

### ISSUE THREAD

**Issue by KIK89** [BeaverUI/ESPJagaBooster#2]
Username and password for mqtt server is missing

**Comment by BeaverUI** [comment]
Done! Please verify the functionality, as my MQTT broker doesn't have secure login configured.

**Comment by KIK89** [comment]
It is working fine! so far i can test is without the base print and ntc sensors!

**Comment by BeaverUI** [comment]
Great. PCBs are incoming! ETA: 2 weeks :-)
